-- MySQL Script generated by MySQL Workbench
-- 05/28/18 12:24:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mundial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mundial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mundial` DEFAULT CHARACTER SET utf8 ;
USE `mundial` ;

-- -----------------------------------------------------
-- Table `mundial`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundial`.`pais` (
  `idpais` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `grupo` VARCHAR(1) NOT NULL,
  `G` INT NOT NULL DEFAULT 0,
  `PTS` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundial`.`partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundial`.`partido` (
  `idpartido` INT NOT NULL,
  `idp1` INT NOT NULL,
  `idp2` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`idpartido`),
  INDEX `idequipo_idx` (`idp1` ASC),
  INDEX `idequipo2_idx` (`idp2` ASC),
  CONSTRAINT `idequipo1`
    FOREIGN KEY (`idp1`)
    REFERENCES `mundial`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idequipo2`
    FOREIGN KEY (`idp2`)
    REFERENCES `mundial`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
